services:
  - docker

addons:
  ssh_known_hosts: cloud.shu.xn--io0a7i

jobs:
  include:
    - stage: build
      language: minimal
      script:
        - docker build -t shu-volunteer .
        - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag shu-volunteer $DOCKER_USERNAME/shu-volunteer:$TRAVIS_BUILD_ID
        - docker push $DOCKER_USERNAME/shu-volunteer
    - stage: deploy
      language: minimal
      before_install:
        - openssl aes-256-cbc -K $encrypted_62138baba9e5_key -iv $encrypted_62138baba9e5_iv
          -in deploy_rsa.enc -out deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 ./deploy_rsa
        - ssh-add ./deploy_rsa
      script:
        - ssh -i ./deploy_rsa root@cloud.shu.xn--io0a7i ./deploy.sh $DOCKER_USERNAME/shu-volunteer:$TRAVIS_BUILD_ID
